server:
  port: 4050

spring:
  rabbitmq:
    host: 106.14.69.75
    port: 5682
    username: pig
    password: lengleng

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023